# Generated by Django 4.2.13 on 2024-06-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customer_user_remove_producer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producercategory'),
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
