# Generated by Django 4.2.13 on 2024-06-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_name_customer_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='producercategory',
            name='address',
            field=models.TextField(default='Dar es salaam'),
        ),
        migrations.AddField(
            model_name='producercategory',
            name='contact_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='producercategory',
            name='contact_phone',
            field=models.CharField(default='074xxxxxxx', max_length=15),
        ),
    ]
