# Generated by Django 4.2.13 on 2024-07-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customer_user_alter_producercategory_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default=11442, max_length=15),
        ),
    ]
