# Generated by Django 4.2.13 on 2024-07-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customer_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='type',
        ),
    ]
