# Generated by Django 4.2.13 on 2024-07-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_energy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Customer'), (3, 'Student')], default=1, max_length=10),
        ),
    ]
